server:
  port: 8080
  servlet:
    context-path: "/"
    session:
      timeout: 720m
  error:
    whitelabel:
      enabled: false

spring:
  main:
    lazy-initialization: true
  application:
    name: "demo"
  datasource:
    hikari:
      maximum-pool-size: 50
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 590000
      minimum-idle: 5
      connection-test-query: "select 1"
      connection-init-sql: set names utf8mb4
    url: "jdbc:mysql://localhost:3306/basic_dev?useLegacyDatetimeCode=false&characterEncoding=utf8"
    username: "root"
    password: "root"
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 10
          order_inserts: true
          order_updates: true
        format_sql: false